# fly.toml app configuration file generated for comp7940-lab5-chatbot-spring-hill-692 on 2024-03-24T17:02:20+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comp7940-lab5-chatbot-spring-hill-692'
primary_region = 'hkg'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  PORT = '8080'

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"
  
  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

[[vm]]
  size = 'shared-cpu-1x'
